// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTCNXN1akZ6DEWKLGyOp2JZvAworux9jI',
    appId: '1:561382074280:web:e3e8ca43e1a5270b519f9d',
    messagingSenderId: '561382074280',
    projectId: 'scu-acm',
    authDomain: 'scu-acm.firebaseapp.com',
    storageBucket: 'scu-acm.appspot.com',
    measurementId: 'G-9ELQ4BE3XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtybdGOkLHKEF3JFNWVKPhHroNefzjP5M',
    appId: '1:561382074280:android:5c4272d33713ca76519f9d',
    messagingSenderId: '561382074280',
    projectId: 'scu-acm',
    storageBucket: 'scu-acm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX_DEcqUuaPUWIncLfvge3oM1w5iUYwOQ',
    appId: '1:561382074280:ios:4bb796bbda8a67b6519f9d',
    messagingSenderId: '561382074280',
    projectId: 'scu-acm',
    storageBucket: 'scu-acm.appspot.com',
    iosClientId: '561382074280-9aoocelieqf05ao91d0qrvrorvn2lile.apps.googleusercontent.com',
    iosBundleId: 'com.example.acmMobile',
  );
}
