// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq18kR-oYedp0N09zlcvzwARVtrnG1T8c',
    appId: '1:984742690738:web:c0daf9450ff26403d76eab',
    messagingSenderId: '984742690738',
    projectId: 'scu-acm-test',
    authDomain: 'scu-acm-test.firebaseapp.com',
    storageBucket: 'scu-acm-test.appspot.com',
    measurementId: 'G-VCHPRFBRNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiFXtfgodeo0bpuqJWgvxm4QdRogx9P6Q',
    appId: '1:984742690738:android:42fba10e0294a4d4d76eab',
    messagingSenderId: '984742690738',
    projectId: 'scu-acm-test',
    storageBucket: 'scu-acm-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBStCPepiGQ7b-uxw0rjCdOkCUv8aKQNHU',
    appId: '1:984742690738:ios:b5ebc4463c5a0ae6d76eab',
    messagingSenderId: '984742690738',
    projectId: 'scu-acm-test',
    storageBucket: 'scu-acm-test.appspot.com',
    iosBundleId: 'com.example.acmMobile',
  );

}